name: Release
on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
    secrets:
      token:
        required: false
      signingKey:
        required: true
      signingKeyPassword:
        required: true
      centralApiUsername:
        required: true
      centralApiPassword:
        required: true
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: Tag (e.g. 0.1.0) or branch to build the release from

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Set version
        run: echo "VERSION=${{ inputs.branch }}" >> $GITHUB_ENV
      - name: Show version
        run: echo "Publishing version ${VERSION}"
      - name: Publish to Maven Central
        run: |
          ./gradlew publishAllToNewMavenCentralApi --info \
            -Psign=true \
            -PautomaticPublish=true \
            -PversionOverride=$VERSION \
            -PsigningKey="${{ secrets.signingKey != '' && secrets.signingKey || secrets.SIGNING_KEY }}" \
            -PsigningKeyPassword="${{ secrets.signingKeyPassword != '' && secrets.signingKeyPassword || secrets.SIGNING_KEY_PASSWORD }}" \
            -PcentralApiUsername="${{ secrets.centralApiUsername != '' && secrets.centralApiUsername || secrets.MAVEN_CENTRAL_USER }}" \
            -PcentralApiPassword="${{ secrets.centralApiPassword != '' && secrets.centralApiPassword || secrets.MAVEN_CENTRAL_PASSWORD }}"
